<script type="text/javascript">
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
		
		  ga('create', 'UA-46754400-1', 'janeullah.com');
		  ga('send', 'pageview');
		
		</script>        
        <!-- Start of StatCounter Code for Default Guide -->
		<script type="text/javascript">
		var sc_project=9502502; 
		var sc_invisible=1; 
		var sc_security="948439ae"; 
		var scJsHost = (("https:" == document.location.protocol) ?
		"https://secure." : "http://www.");
		document.write("<sc"+"ript type='text/javascript' src='" +
		scJsHost+
		"statcounter.com/counter/counter.js'></"+"script>");
		</script>
		<noscript><div class="statcounter"><a title="free hit
		counter" href="http://statcounter.com/free-hit-counter/"
		target="_blank"><img class="statcounter"
		src="http://c.statcounter.com/9502502/0/948439ae/1/"
		alt="free hit counter"></a></div></noscript>
		<!-- End of StatCounter Code for Default Guide -->