    <script src="<?php echo $asseturl ."/js/jquery-1.9.1.min.js"; ?>"></script>
    <script src="<?php echo $asseturl ."/js/bootstrap.min.js"; ?>"></script>
    <script src="<?php echo $asseturl ."/js/alertify.min.js"; ?>"></script>
    <script src="<?php echo $asseturl ."/js/dawgspeak.js"; ?>"></script>
    <link href="<?php echo $asseturl ."/css/bootstrap.min.css"; ?>" rel="stylesheet">
    <link href="<?php echo $asseturl ."/css/alertify.core.css"; ?>"  rel="stylesheet" media="screen">
    <link href="<?php echo $asseturl ."/css/alertify.default.css"; ?>"  rel="stylesheet" media="screen">
    <link href="<?php echo $asseturl ."/css/bootstrap-responsive.css"; ?>" rel="stylesheet">
    <link href="<?php echo $asseturl ."/css/dawgspeak.css"; ?>" rel="stylesheet">
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://apps.janeullah.com/coursepicker/assets/js/html5shiv.js"></script>
    <![endif]-->
    <!--[if IE]><script type="text/javascript" src="http://apps.janeullah.com/coursepicker/assets/js/excanvas.js"></script><![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?php echo $asseturl ."/ico/apple-touch-icon-144-precomposed.png";?>">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?php echo $asseturl ."/ico/apple-touch-icon-114-precomposed.png";?>">
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?php echo $asseturl ."/ico/apple-touch-icon-72-precomposed.png";?>">
    <link rel="apple-touch-icon-precomposed" href="<?php echo $asseturl ."/ico/apple-touch-icon-57-precomposed.png";?>">
    <link rel="shortcut icon" href="<?php echo $asseturl ."assets/ico/favicon.png";?>">
